language: node_js

before_script:
  - npm install -g web-component-tester

addons:
 firefox: '46.0'
 apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

script:
  - xvfb-run wct --npm
