language: node_js
node_js:
  - "7"
before_script:
  - npm install -g web-component-tester
addons:
 firefox: latest
 apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

script:
  - xvfb-run wct --npm
