language: node_js
dist: trusty
sudo: required
addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - "7"
cache:
  directories:
    - node_modules
install:
  - npm install -g web-component-tester
  - npm install
script:
  - xvfb-run npm run test
