language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
  - npm install -g web-component-tester bower polymer-cli
  - bower install
  - export PATH=$PWD/node_modules/.bin:$PATH
script:
  - xvfb-run polymer test
