name: Bundle

# on:
#   release:
#     types:
#       - created
#       - published
#       - prereleased
#       - released

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Comma separated list of release tags'
        required: true 
        type: string

jobs:
  bundle:
    # Prevents changesets action from creating a PR on forks
    if: github.repository == 'patternfly/patternfly-elements'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Install packages
        run: npm i --prefer-offline

      - name: Bundle
        id: bundle
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const bundle = require('./scripts/bundle-release.cjs');
            const tags = '${{ github.event.inputs.tags }}';
            const workspace = '${{ github.workspace }}';
            await bundle({ core, github, glob, tags, workspace });
