name: Bundle

on:
  release:
    types:
      - published

jobs:
  release:
    # Prevents changesets action from creating a PR on forks
    if: github.repository == 'patternfly/patternfly-elements'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Install packages
        run: npm i --prefer-offline

      - name: Bundle
        id: bundle
        if: ${{ steps.changesets.outputs.published }}
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const bundle = require('./scripts/bundle-release.cjs');
            await bundle({ context, github, glob, workspace: '${{ github.workspace }}' });
